"use client";
import {adminFetch} from "@/lib/admin-fetch";
import {useCallback,useEffect,useState} from "react";
import {Loader2,Save,Sparkles} from "lucide-react";
import {apiError} from "@/lib/api-error";

type Settings={company_name:string;email:string;mobile:string;website:string;default_cta:string;show_email:number;show_mobile:number;show_website:number};
type Creative={id:string;creative_date:string;theme:string;headline:string;caption:string;cta:string;hashtags:string;image_prompt:string;campaign_type:string;image_generation_available:boolean;status:string};

export default function AdminAiCreatives(){
  const[settings,setSettings]=useState<Settings|null>(null),[items,setItems]=useState<Creative[]>([]),[busy,setBusy]=useState(false),[notice,setNotice]=useState("");
  const load=useCallback(async()=>{try{const[a,b]=await Promise.all([adminFetch("/api/admin/creative-settings"),adminFetch("/api/admin/creatives")]);if(!a.ok)throw await apiError(a,"Creative settings could not be loaded");if(!b.ok)throw await apiError(b,"Generation history could not be loaded");setSettings((await a.json()).settings);setItems((await b.json()).creatives)}catch(error){setNotice(error instanceof Error?error.message:"Marketing data could not be loaded.")}},[]);
  useEffect(()=>{void load()},[load]);
  async function save(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setNotice("");try{const response=await adminFetch("/api/admin/creative-settings",{method:"POST",body:new FormData(event.currentTarget)});if(!response.ok)throw await apiError(response,"Branding settings could not be saved");setNotice("Branding settings saved.");await load()}catch(error){setNotice(error instanceof Error?error.message:"Branding settings could not be saved.")}finally{setBusy(false)}}
  async function generate(){if(busy)return;setBusy(true);setNotice("");try{const response=await adminFetch("/api/admin/creatives",{method:"POST",headers:{"Content-Type":"application/json"},body:"{}"});if(!response.ok)throw await apiError(response,"Creative generation failed");const payload=await response.json();setNotice(payload.message||"Marketing content generated successfully.");await load()}catch(error){setNotice(error instanceof Error?error.message:"Creative generation failed.")}finally{setBusy(false)}}
  async function approve(id:string){try{const response=await adminFetch("/api/admin/creatives",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id,status:"approved"})});if(!response.ok)throw await apiError(response,"Creative approval failed");await load()}catch(error){setNotice(error instanceof Error?error.message:"Creative approval failed.")}}
  return <section className="admin-panel creative-admin"><div className="admin-panel-head"><div><h2>Marketing / AI Creative Settings</h2><p>APInex generates campaign content and a professional image prompt. Image generation is not available from this configured provider.</p></div><button className="button" onClick={()=>void generate()} disabled={busy}><Sparkles size={16}/>Generate today</button></div>{notice&&<div className="admin-notice">{notice}</div>}{settings&&<form className="creative-settings" onSubmit={save}><label>Company logo<input type="file" name="logo" accept="image/jpeg,image/png,image/webp,image/avif"/></label><label>Company name<input name="companyName" defaultValue={settings.company_name} required/></label><label>Email ID<input type="email" name="email" defaultValue={settings.email} required/></label><label>Mobile number<input name="mobile" defaultValue={settings.mobile} placeholder="Enter a verified company number"/></label><label>Website URL<input name="website" defaultValue={settings.website}/></label><label>Default CTA<input name="defaultCta" defaultValue={settings.default_cta} required/></label><div className="creative-toggles"><label><input type="checkbox" name="showEmail" value="true" defaultChecked={Boolean(settings.show_email)}/> Show email</label><label><input type="checkbox" name="showMobile" value="true" defaultChecked={Boolean(settings.show_mobile)}/> Show mobile</label><label><input type="checkbox" name="showWebsite" value="true" defaultChecked={Boolean(settings.show_website)}/> Show website</label></div><button className="button" disabled={busy}>{busy?<Loader2 className="spin" size={16}/>:<Save size={16}/>} Save branding</button></form>}<div className="creative-history"><h3>Generation history</h3>{items.map(item=><article key={item.id}><div><span>{item.creative_date} · {item.status} · Content + image prompt</span><h4>{item.headline}</h4><p>{item.caption}</p><p><strong>CTA:</strong> {item.cta}</p><p><strong>Hashtags:</strong> {item.hashtags}</p><p><strong>Image prompt:</strong> {item.image_prompt}</p><small>{item.theme} · {item.campaign_type}</small><div>{item.status!=="approved"&&<button className="button button-ghost" onClick={()=>void approve(item.id)}>Approve</button>}</div></div></article>)}{!items.length&&<p className="admin-empty">No marketing content yet. Generate today to create a campaign.</p>}</div></section>
}
