/* eslint-disable @next/next/no-img-element */
"use client";
import {useCallback,useEffect,useState} from "react";import {Download,Loader2,Save,Send,Sparkles} from "lucide-react";
type Settings={company_name:string;email:string;mobile:string;website:string;default_cta:string;show_email:number;show_mobile:number;show_website:number};type Creative={id:number;creative_date:string;theme:string;headline:string;caption:string;status:string;image_size:number};
async function creativePng(item:Creative){const response=await fetch(`/api/admin/creatives/${item.id}/file`);if(!response.ok)throw new Error("Creative could not be downloaded.");const svgUrl=URL.createObjectURL(await response.blob());try{const image=new Image();image.src=svgUrl;await image.decode();const canvas=document.createElement("canvas");canvas.width=1080;canvas.height=1080;canvas.getContext("2d")?.drawImage(image,0,0,1080,1080);return await new Promise<Blob>((resolve,reject)=>canvas.toBlob(blob=>blob?resolve(blob):reject(new Error("PNG export failed.")),"image/png",1))}finally{URL.revokeObjectURL(svgUrl)}}
export default function AdminAiCreatives(){const[settings,setSettings]=useState<Settings|null>(null),[items,setItems]=useState<Creative[]>([]),[busy,setBusy]=useState(false),[notice,setNotice]=useState("");const load=useCallback(async()=>{const[a,b]=await Promise.all([fetch("/api/admin/creative-settings"),fetch("/api/admin/creatives")]);if(a.ok)setSettings((await a.json()).settings);if(b.ok)setItems((await b.json()).creatives)},[]);useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer)},[load]);
async function save(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);const response=await fetch("/api/admin/creative-settings",{method:"POST",body:new FormData(event.currentTarget)}),data=await response.json();setNotice(response.ok?"Branding settings saved. Future creatives will use these latest details.":data.error);setBusy(false);if(response.ok)void load()}
async function generate(){setBusy(true);const response=await fetch("/api/admin/creatives",{method:"POST",headers:{"Content-Type":"application/json"},body:"{}"}),data=await response.json();setNotice(response.ok?"Today’s branded creative was generated and saved.":data.error);setBusy(false);if(response.ok)void load()}
async function approve(id:number){await fetch("/api/admin/creatives",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id,status:"approved"})});void load()}
async function download(item:Creative){try{const blob=await creativePng(item),url=URL.createObjectURL(blob),link=document.createElement("a");link.href=url;link.download=`Solarious_Daily_Creative_${item.creative_date}.png`;link.click();URL.revokeObjectURL(url)}catch(error){setNotice(error instanceof Error?error.message:"Download failed.")}}
async function share(item:Creative){try{const blob=await creativePng(item),file=new File([blob],`Solarious_Daily_Creative_${item.creative_date}.png`,{type:"image/png"});if(navigator.share&&navigator.canShare?.({files:[file]}))await navigator.share({title:item.headline,text:item.caption,files:[file]});else window.open(`https://wa.me/?text=${encodeURIComponent(`${item.headline}\n${item.caption}`)}`,"_blank","noopener,noreferrer")}catch(error){if((error as Error).name!=="AbortError")setNotice("Sharing could not be started. Download the creative and attach it manually.")}}
return <section className="admin-panel creative-admin"><div className="admin-panel-head"><div><h2>Marketing / AI Creative Settings</h2><p>Every saved creative renders the latest approved logo and contact settings into the final image.</p></div><button className="button" onClick={()=>void generate()} disabled={busy}><Sparkles size={16}/>Generate today</button></div>{notice&&<div className="admin-notice">{notice}</div>}{settings&&<form className="creative-settings" onSubmit={save}><label>Company logo<input type="file" name="logo" accept="image/jpeg,image/png,image/webp,image/avif"/></label><label>Company name<input name="companyName" defaultValue={settings.company_name} required/></label><label>Email ID<input type="email" name="email" defaultValue={settings.email} required/></label><label>Mobile number<input name="mobile" defaultValue={settings.mobile} placeholder="Enter a verified company number" required/></label><label>Website URL<input name="website" defaultValue={settings.website}/></label><label>Default CTA<input name="defaultCta" defaultValue={settings.default_cta} required/></label><div className="creative-toggles"><label><input type="checkbox" name="showEmail" value="true" defaultChecked={Boolean(settings.show_email)}/> Show email</label><label><input type="checkbox" name="showMobile" value="true" defaultChecked={Boolean(settings.show_mobile)}/> Show mobile</label><label><input type="checkbox" name="showWebsite" value="true" defaultChecked={Boolean(settings.show_website)}/> Show website</label></div><p className="assumption">A verified email and mobile number must be enabled before generation. No unverified number is published.</p><button className="button" disabled={busy}>{busy?<Loader2 className="spin" size={16}/>:<Save size={16}/>} Save branding</button></form>}<div className="creative-history"><h3>Generation history</h3>{items.map(item=><article key={item.id}><img src={`/api/admin/creatives/${item.id}/file`} alt={item.headline}/><div><span>{item.creative_date} · {item.status}</span><h4>{item.headline}</h4><p>{item.caption}</p><small>{item.theme} · {Math.ceil(item.image_size/1024)} KB</small><div><button className="button button-ghost" onClick={()=>void download(item)}><Download size={15}/> Download Creative</button>{item.status!=="approved"&&<button className="button button-ghost" onClick={()=>void approve(item.id)}>Approve</button>}<button className="button button-ghost" onClick={()=>void share(item)}><Send size={15}/> Share / WhatsApp</button></div></div></article>)}{!items.length&&<p className="admin-empty">No creatives yet. Save verified branding, then generate today’s creative.</p>}</div></section>}
