"use client";
import { useMemo, useState } from "react";
import Link from "next/link";
import { ArrowRight, SearchCheck } from "lucide-react";
import ToolPageShell from "@/components/tool-page-shell";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";

export default function ModuleRecommender(){
  const [project,setProject]=useState("commercial"); const [space,setSpace]=useState("balanced"); const [priority,setPriority]=useState("efficiency");
  const result=useMemo(()=>{ if(project==="utility"&&space==="open") return {name:"Bifacial",why:"Ground-mounted projects with suitable rear-side irradiance may benefit from bifacial architecture.",alt:"TOPCon"}; if(priority==="efficiency") return {name:"TOPCon",why:"A performance-focused category for projects that prioritise module efficiency and long-term energy yield.",alt:"HJT"}; return {name:"Mono PERC",why:"A widely used category for practical commercial and industrial applications.",alt:"TOPCon"};},[project,space,priority]);
  return <ToolPageShell eyebrow="Structured module guidance" title="Find the Right Solar Module" intro="Answer three project questions to receive preliminary category guidance—not a substitute for engineering design."><section className="tool-workspace"><div className="tool-form"><label>Project type<Select value={project} onValueChange={setProject}><SelectTrigger className="tool-select"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="commercial">Commercial rooftop</SelectItem><SelectItem value="industrial">Industrial</SelectItem><SelectItem value="utility">Utility scale</SelectItem></SelectContent></Select></label><label>Available space<Select value={space} onValueChange={setSpace}><SelectTrigger className="tool-select"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="limited">Space constrained</SelectItem><SelectItem value="balanced">Balanced</SelectItem><SelectItem value="open">Open ground area</SelectItem></SelectContent></Select></label><label>Primary priority<Select value={priority} onValueChange={setPriority}><SelectTrigger className="tool-select"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="efficiency">Higher efficiency</SelectItem><SelectItem value="value">Practical value</SelectItem><SelectItem value="bifacial">Rear-side generation potential</SelectItem></SelectContent></Select></label><p className="assumption">Recommendation logic uses category-level characteristics only. Final selection requires site and product review.</p></div><div className="tool-result"><SearchCheck size={28}/><span className="result-label">Preliminary recommendation</span><strong>{result.name}</strong><p>{result.why}</p><dl><div><dt>Alternative category</dt><dd>{result.alt}</dd></div><div><dt>Next step</dt><dd>Technical consultation</dd></div></dl><Link className="button" href="/contact#quote">Discuss with solar engineer <ArrowRight size={16}/></Link></div></section></ToolPageShell>;
}
