"use client";
import Image from "next/image";
import Link from "next/link";
import { ChevronDown, Menu } from "lucide-react";
import { Sheet, SheetContent, SheetHeader, SheetTitle, SheetTrigger } from "@/components/ui/sheet";

const primary=[['Home','/'],['About','/about'],['Manufacturing','/manufacturing'],['Technology','/technology'],['Projects','/projects'],['Resources','/resources'],['Contact','/contact']] as const;
const productLinks=[['All Products','/products'],['Mono PERC','/products/mono-perc'],['TOPCon','/products/topcon'],['HJT','/products/hjt'],['Bifacial','/products/bifacial']] as const;
const solutionLinks=[['Solar Calculator','/solar-calculator'],['Find Your Module','/module-recommender'],['Compare Modules','/compare']] as const;

export default function SiteHeader(){return <header className="site-header global-header"><Link href="/" className="brand" aria-label="Solarious Energy home"><Image src="/solarious-logo.jpeg" alt="Solarious Energy" width={236} height={86} priority /></Link><nav className="desktop-nav" aria-label="Primary navigation"><Link href="/">Home</Link><Link href="/about">About</Link><details className="nav-dropdown"><summary>Products <ChevronDown size={14}/></summary><div>{productLinks.map(([label,href])=><Link key={href} href={href}>{label}</Link>)}</div></details><Link href="/manufacturing">Manufacturing</Link><Link href="/technology">Technology</Link><Link href="/projects">Projects</Link><details className="nav-dropdown"><summary>Solutions <ChevronDown size={14}/></summary><div>{solutionLinks.map(([label,href])=><Link key={href} href={href}>{label}</Link>)}</div></details><Link href="/resources">Resources</Link><Link href="/contact">Contact</Link></nav><Link href="/quote" className="button button-small">Get a quote</Link><Sheet><SheetTrigger asChild><button className="menu-button" aria-label="Open navigation"><Menu size={22}/></button></SheetTrigger><SheetContent side="right" className="mobile-sheet"><SheetHeader><SheetTitle>Solarious Energy</SheetTitle></SheetHeader><nav aria-label="Mobile navigation">{primary.map(([label,href])=><Link key={href} href={href}>{label}</Link>)}<p>Products</p>{productLinks.map(([label,href])=><Link key={href} href={href}>{label}</Link>)}<p>Solutions</p>{solutionLinks.map(([label,href])=><Link key={href} href={href}>{label}</Link>)}<Link className="button" href="/quote">Get a quote</Link></nav></SheetContent></Sheet></header>}
