"use client";
import { useMemo, useState } from "react";
import { Calculator } from "lucide-react";
import ToolPageShell from "@/components/tool-page-shell";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";

export default function SolarCalculator() {
  const [project, setProject] = useState("commercial"); const [capacity, setCapacity] = useState(100); const [modulePower, setModulePower] = useState(550); const [area, setArea] = useState(2.6);
  const output = useMemo(() => ({ quantity: Math.ceil(capacity * 1000 / Math.max(modulePower, 1)), area: Math.ceil(Math.ceil(capacity * 1000 / Math.max(modulePower, 1)) * area), technology: project === "utility" ? "TOPCon or Bifacial" : project === "industrial" ? "TOPCon or Mono PERC" : "Mono PERC or TOPCon" }), [project, capacity, modulePower, area]);
  return <ToolPageShell eyebrow="Digital project planning" title="Solar Project Calculator" intro="Create a transparent preliminary module and area estimate. Adjust the engineering assumptions to match your project data."><section className="tool-workspace"><div className="tool-form"><label>Project type<Select value={project} onValueChange={setProject}><SelectTrigger className="tool-select"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="commercial">Commercial rooftop</SelectItem><SelectItem value="industrial">Industrial</SelectItem><SelectItem value="utility">Utility scale</SelectItem></SelectContent></Select></label><label>Required system capacity (kW)<input type="number" min="1" value={capacity} onChange={(e) => setCapacity(Number(e.target.value))} /></label><label>Assumed module power (W)<input type="number" min="1" value={modulePower} onChange={(e) => setModulePower(Number(e.target.value))} /></label><label>Assumed area per module (m²)<input type="number" min="1" step="0.1" value={area} onChange={(e) => setArea(Number(e.target.value))} /></label><p className="assumption">Use confirmed Solarious module values when available. This calculator does not estimate cost, savings or subsidy.</p></div><div className="tool-result"><Calculator size={28} /><span className="result-label">Preliminary estimate</span><strong>{capacity || 0} kW</strong><dl><div><dt>Approximate modules</dt><dd>{Number.isFinite(output.quantity) ? output.quantity : 0}</dd></div><div><dt>Approximate module area</dt><dd>{Number.isFinite(output.area) ? output.area : 0} m²</dd></div><div><dt>Suggested category</dt><dd>{output.technology}</dd></div></dl><p>Preliminary estimate only. Final engineering calculations require technical assessment.</p><a className="button" href="/contact#quote">Request detailed proposal</a></div></section></ToolPageShell>;
}
