"use client";

import { ChevronLeft, ChevronRight } from "lucide-react";
import { useCallback, useEffect, useRef, useState } from "react";

type Member = { id:string; name:string; designation:string; short_info:string; photo_url:string; linkedin_url:string };

const LinkedInIcon=({className="h-4 w-4"}:{className?:string})=><svg viewBox="0 0 24 24" className={className} fill="currentColor" aria-hidden="true"><path d="M20.45 20.45h-3.56v-5.57c0-1.33-.03-3.04-1.85-3.04-1.85 0-2.14 1.45-2.14 2.94v5.67H9.34V9h3.42v1.56h.05c.48-.9 1.64-1.85 3.37-1.85 3.6 0 4.27 2.37 4.27 5.46v6.28zM5.32 7.43a2.07 2.07 0 1 1 0-4.14 2.07 2.07 0 0 1 0 4.14zM7.1 20.45H3.54V9H7.1v11.45zM22.23 0H1.77C.79 0 0 .77 0 1.72v20.56C0 23.23.79 24 1.77 24h20.46c.98 0 1.77-.77 1.77-1.72V1.72C24 .77 23.21 0 22.23 0z" /></svg>;

export default function TeamSection(){
  const[members,setMembers]=useState<Member[]>([]),[status,setStatus]=useState<"loading"|"ready"|"error">("loading"),[active,setActive]=useState(0),[paused,setPaused]=useState(false);
  const viewport=useRef<HTMLDivElement>(null),touchStart=useRef<number|null>(null);
  useEffect(()=>{const controller=new AbortController();fetch("/api/team",{signal:controller.signal}).then(async response=>{if(!response.ok)throw new Error(`Team request failed (${response.status})`);const data=await response.json() as {members?:Member[]};setMembers(Array.isArray(data.members)?data.members:[]);setStatus("ready")}).catch((error:unknown)=>{if(error instanceof DOMException&&error.name==="AbortError")return;console.error("Unable to load published team members:",error);setStatus("error")});return()=>controller.abort()},[]);
  const goTo=useCallback((index:number,behavior:ScrollBehavior="smooth")=>{if(!members.length||!viewport.current)return;const next=(index+members.length)%members.length,card=viewport.current.querySelector<HTMLElement>(`[data-team-index="${next}"]`);if(!card)return;viewport.current.scrollTo({left:card.offsetLeft-(viewport.current.clientWidth-card.clientWidth)/2,behavior});setActive(next)},[members.length]);
  useEffect(()=>{if(members.length<2||paused||window.matchMedia("(prefers-reduced-motion: reduce)").matches)return;const timer=window.setInterval(()=>goTo(active+1),5000);return()=>window.clearInterval(timer)},[active,goTo,members.length,paused]);
  const syncActiveCard=()=>{if(!viewport.current||!members.length)return;const center=viewport.current.scrollLeft+viewport.current.clientWidth/2;let nearest=0,distance=Number.POSITIVE_INFINITY;viewport.current.querySelectorAll<HTMLElement>("[data-team-index]").forEach(card=>{const candidate=Number(card.dataset.teamIndex),cardCenter=card.offsetLeft+card.clientWidth/2;if(Math.abs(cardCenter-center)<distance){distance=Math.abs(cardCenter-center);nearest=candidate}});setActive(nearest)};
  if(status==="loading")return <section className="team-section team-state" aria-busy="true"><p>Loading our team…</p></section>;
  if(status==="error"||!members.length)return null;
  return <section className="team-section" aria-labelledby="team-heading"><div className="team-carousel-head"><div><p className="eyebrow"><span/>People behind Solarious</p><h2 id="team-heading">Meet <em>Our Team</em></h2></div>{members.length>1&&<div className="team-carousel-controls" aria-label="Team carousel controls"><button type="button" onClick={()=>goTo(active-1)} aria-label="Previous team member"><ChevronLeft size={20}/></button><button type="button" onClick={()=>goTo(active+1)} aria-label="Next team member"><ChevronRight size={20}/></button></div>}</div><div className="team-carousel-viewport" ref={viewport} tabIndex={0} role="region" aria-roledescription="carousel" aria-label="Solarious leadership team" onScroll={syncActiveCard} onMouseEnter={()=>setPaused(true)} onMouseLeave={()=>setPaused(false)} onFocusCapture={()=>setPaused(true)} onBlurCapture={event=>{if(!event.currentTarget.contains(event.relatedTarget as Node|null))setPaused(false)}} onTouchStart={event=>{touchStart.current=event.changedTouches[0]?.clientX??null}} onTouchEnd={event=>{const start=touchStart.current,end=event.changedTouches[0]?.clientX;touchStart.current=null;if(start===null||end===undefined||Math.abs(start-end)<42)return;goTo(active+(start>end?1:-1))}} onKeyDown={event=>{if(event.key==="ArrowRight"){event.preventDefault();goTo(active+1)}if(event.key==="ArrowLeft"){event.preventDefault();goTo(active-1)}}}><div className="team-carousel-track"><div className="team-carousel-gutter" aria-hidden="true"/>{members.map((member,index)=><article className={`team-story ${active===index?"is-active":""}`} key={member.id} data-team-index={index} aria-roledescription="slide" aria-label={`${index+1} of ${members.length}`}><div className="team-story-copy"><span className="team-quote" aria-hidden="true">“</span><p>{member.short_info}</p><div className="team-story-person"><strong>{member.name}</strong><span>{member.designation}</span>{member.linkedin_url&&<a href={member.linkedin_url} target="_blank" rel="noreferrer" aria-label={`${member.name} on LinkedIn`}><LinkedInIcon/><span>LinkedIn</span></a>}</div></div><div className="team-story-image"><img src={member.photo_url||"/team-avatar.svg"} alt={member.name} loading={index===0?"eager":"lazy"} decoding="async" onError={event=>{event.currentTarget.src="/team-avatar.svg"}}/></div></article>)}<div className="team-carousel-gutter" aria-hidden="true"/></div></div></section>;
}
