import "server-only";
import { runtimeEnv as env } from "@/lib/runtime-env";

export type Branding={company_name:string;email:string;mobile:string;website:string;default_cta:string;logo_key:string|null;logo_type:string|null;show_email:number;show_mobile:number;show_website:number};
const themes=[
  ["Smart Solar Performance","Power Every Possibility","High-efficiency solar technology engineered for dependable energy and confident project planning."],
  ["Clean Energy Future","Progress Powered by the Sun","Advanced solar modules help businesses build a cleaner, more resilient energy future."],
  ["Industrial Solar Excellence","Engineered for Greater Output","Modern module technology, disciplined manufacturing and intelligent performance for ambitious projects."],
  ["Solar for Every Project","The Right Energy. The Right Scale.","From commercial rooftops to utility-scale installations, choose solar technology built for performance."],
  ["Next-Generation Modules","Smarter Modules. Stronger Returns.","Explore high-performance solar solutions designed for long-term generation and project value."],
  ["Made for India","Reliable Energy Starts Here","Solar modules designed for demanding conditions, consistent output and a sustainable tomorrow."],
] as const;
const esc=(v:string)=>v.replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&apos;"}[c]!));
const b64=(bytes:ArrayBuffer)=>{let out="";for(const b of new Uint8Array(bytes))out+=String.fromCharCode(b);return btoa(out)};
async function imageData(request:Request,path:string,type="image/jpeg"){const response=await fetch(new URL(path,request.url));if(!response.ok)return "";return `data:${response.headers.get("content-type")||type};base64,${b64(await response.arrayBuffer())}`}
async function aiSolarBackground(theme:string,creativeDate:string){const key=process.env.OPENAI_API_KEY;if(!key)return "";const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),90000);try{const response=await fetch("https://api.openai.com/v1/images/generations",{method:"POST",headers:{Authorization:`Bearer ${key}`,"Content-Type":"application/json"},body:JSON.stringify({model:process.env.OPENAI_IMAGE_MODEL||"gpt-image-1",prompt:`Create a unique premium photorealistic corporate solar-energy social-media background for ${theme}, dated ${creativeDate}. Modern solar farm or module manufacturing environment, subtle intelligent energy analytics and smart-grid overlays, clean professional composition, dark blue and solar-orange accents, no people, no robots, no logos, no words, no letters, square composition. Keep the upper-left and lower section visually calm for brand overlays.`,size:"1024x1024",quality:"high",output_format:"png"}),signal:controller.signal});if(!response.ok)throw new Error(`AI image service returned ${response.status}.`);const data=await response.json() as {data?:Array<{b64_json?:string}>};const encoded=data.data?.[0]?.b64_json;if(!encoded)throw new Error("AI image service returned no image.");return `data:image/png;base64,${encoded}`}finally{clearTimeout(timer)}}
export async function createDailyCreative(request:Request,forcedTheme?:string){
 const settings=await env.DB.prepare("SELECT * FROM creative_brand_settings WHERE id=1").first<Branding>();if(!settings)throw new Error("Brand settings are unavailable");
 if(!settings.email||!settings.show_email)throw new Error("Enable a verified company email in AI Creative Settings before generation.");
 if(!settings.mobile||!settings.show_mobile)throw new Error("Add and enable a verified company mobile number in AI Creative Settings before generation.");
 const creativeDate=new Date().toISOString().slice(0,10),seed=[...creativeDate].reduce((sum,char)=>sum+char.charCodeAt(0),0),picked=forcedTheme?themes.find(x=>x[0]===forcedTheme)||themes[seed%themes.length]:themes[seed%themes.length];
 const [baseTheme,baseHeadline,baseCaption]=picked,dateLabel=new Date(`${creativeDate}T00:00:00Z`).toLocaleDateString("en-GB",{day:"2-digit",month:"short",year:"numeric",timeZone:"UTC"}),theme=`${baseTheme} · ${dateLabel}`,headline=`${baseHeadline} — ${dateLabel}`,caption=`${baseCaption} Daily Solarious insight for ${dateLabel}.`;const background=await aiSolarBackground(baseTheme,creativeDate)||await imageData(request,"/utility-solar.webp","image/webp");let logo="";
 if(settings.logo_key){const object=await env.BUCKET.get(settings.logo_key);if(object)logo=`data:${settings.logo_type||"image/png"};base64,${b64(await object.arrayBuffer())}`;}if(!logo)logo=await imageData(request,"/solarious-logo.jpeg");
 const contacts=[settings.show_email&&settings.email?`✉ ${settings.email}`:"",settings.show_mobile&&settings.mobile?`☎ ${settings.mobile}`:"",settings.show_website&&settings.website?settings.website:""].filter(Boolean);
 const svg=`<svg xmlns="http://www.w3.org/2000/svg" width="1080" height="1080" viewBox="0 0 1080 1080"><defs><linearGradient id="shade" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="#071d31" stop-opacity=".08"/><stop offset=".7" stop-color="#071d31" stop-opacity=".2"/><stop offset="1" stop-color="#071d31" stop-opacity=".82"/></linearGradient><linearGradient id="foot" x1="0" x2="1"><stop stop-color="#071d31"/><stop offset="1" stop-color="#123f5a"/></linearGradient></defs><rect width="1080" height="1080" fill="#e9f2f5"/>${background?`<image href="${background}" width="1080" height="1080" preserveAspectRatio="xMidYMid slice"/>`:""}<rect width="1080" height="1080" fill="url(#shade)"/><rect x="54" y="42" width="370" height="116" rx="18" fill="#fff" fill-opacity=".94"/>${logo?`<image href="${logo}" x="76" y="61" width="326" height="78" preserveAspectRatio="xMidYMid meet"/>`:""}<text x="62" y="735" fill="#f5a623" font-family="Arial" font-size="25" font-weight="700" letter-spacing="4">${esc(theme.toUpperCase())}</text><text x="62" y="810" fill="#fff" font-family="Georgia" font-size="58" font-weight="700">${esc(headline)}</text><text x="64" y="858" fill="#fff" font-family="Arial" font-size="25">${esc(caption.slice(0,92))}</text><rect y="900" width="1080" height="180" fill="url(#foot)"/><text x="58" y="955" fill="#fff" font-family="Arial" font-size="27" font-weight="700">${esc(settings.company_name)}</text>${contacts.map((x,i)=>`<text x="58" y="${997+i*32}" fill="#dce8ee" font-family="Arial" font-size="21">${esc(x)}</text>`).join("")}<rect x="744" y="950" width="278" height="72" rx="12" fill="#ef7d00"/><text x="883" y="995" text-anchor="middle" fill="#fff" font-family="Arial" font-size="23" font-weight="700">${esc(settings.default_cta)}</text></svg>`;
 const bytes=new TextEncoder().encode(svg);return{settings,theme,headline,caption,bytes};
}
