import { NextResponse } from "next/server";import { env } from "cloudflare:workers";import { getAdminUser } from "@/lib/admin-auth";
const categories=["Product Datasheets","Brochures","Warranty Documents","Certificates","Installation Guides","Maintenance Guides","Company Profile","Technical Documents"];
const allowed=new Set(["application/pdf","application/msword","application/vnd.openxmlformats-officedocument.wordprocessingml.document","application/vnd.ms-excel","application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"]);const max=20*1024*1024;
const clean=(v:FormDataEntryValue|null,n=500)=>typeof v==="string"?v.trim().slice(0,n):"";
async function auth(){return Boolean(await getAdminUser())}
export async function GET(){if(!(await auth()))return NextResponse.json({error:"Unauthorized"},{status:401});const rows=await env.DB.prepare("SELECT * FROM resources ORDER BY display_order,created_at DESC").all();return NextResponse.json({resources:rows.results,categories})}
export async function POST(request:Request){if(!(await auth()))return NextResponse.json({error:"Unauthorized"},{status:401});const form=await request.formData();const id=Number(clean(form.get("id"),20))||null;const title=clean(form.get("title"),160),description=clean(form.get("description"),1200),category=clean(form.get("category"),100),product=clean(form.get("product"),80),order=Number(clean(form.get("displayOrder"),10))||0,published=clean(form.get("published"),10)==="true"?1:0;const file=form.get("file");if(!title||!categories.includes(category))return NextResponse.json({error:"Title and valid category are required."},{status:400});const existing=id?await env.DB.prepare("SELECT * FROM resources WHERE id=?").bind(id).first<Record<string,unknown>>():null;if(id&&!existing)return NextResponse.json({error:"Resource not found"},{status:404});let fileKey=existing?.file_key as string|undefined,fileName=existing?.file_name as string|undefined,fileType=existing?.file_type as string|undefined,fileSize=existing?.file_size as number|undefined;if(file instanceof File&&file.size){if(file.size>max||!allowed.has(file.type))return NextResponse.json({error:"Upload PDF, DOC, DOCX, XLS or XLSX up to 20 MB."},{status:400});const key=`resources/${crypto.randomUUID()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,"_")}`;await env.BUCKET.put(key,file.stream(),{httpMetadata:{contentType:file.type},customMetadata:{originalName:file.name}});if(fileKey)await env.BUCKET.delete(fileKey);fileKey=key;fileName=file.name;fileType=file.type;fileSize=file.size}if(!fileKey||!fileName||!fileType||fileSize==null)return NextResponse.json({error:"A document file is required."},{status:400});const now=new Date().toISOString();if(id){await env.DB.prepare("UPDATE resources SET title=?,description=?,category=?,product=?,file_key=?,file_name=?,file_type=?,file_size=?,published=?,display_order=?,updated_at=? WHERE id=?").bind(title,description,category,product,fileKey,fileName,fileType,fileSize,published,order,now,id).run();return NextResponse.json({ok:true,id})}const result=await env.DB.prepare("INSERT INTO resources(title,description,category,product,file_key,file_name,file_type,file_size,published,display_order,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)").bind(title,description,category,product,fileKey,fileName,fileType,fileSize,published,order,now,now).run();return NextResponse.json({ok:true,id:result.meta.last_row_id},{status:201})}
export async function PATCH(request:Request){if(!(await auth()))return NextResponse.json({error:"Unauthorized"},{status:401});const body=await request.json() as {id?:number;published?:boolean};if(!body.id||typeof body.published!=="boolean")return NextResponse.json({error:"Invalid request"},{status:400});await env.DB.prepare("UPDATE resources SET published=?,updated_at=? WHERE id=?").bind(body.published?1:0,new Date().toISOString(),body.id).run();return NextResponse.json({ok:true})}
export async function DELETE(request:Request){if(!(await auth()))return NextResponse.json({error:"Unauthorized"},{status:401});const id=Number(new URL(request.url).searchParams.get("id"));const row=await env.DB.prepare("SELECT file_key,thumbnail_key FROM resources WHERE id=?").bind(id).first<{file_key:string;thumbnail_key:string|null}>();if(!row)return NextResponse.json({error:"Not found"},{status:404});await env.DB.prepare("DELETE FROM resources WHERE id=?").bind(id).run();await env.BUCKET.delete(row.file_key);if(row.thumbnail_key)await env.BUCKET.delete(row.thumbnail_key);return NextResponse.json({ok:true})}
